"$schema" = "https://json.schemastore.org/prettierrc.json"
printWidth = 1024
tabWidth = 4
useTabs = false
semi = true
singleQuote = false
quoteProps = "as-needed"
jsxSingleQuote = false
trailingComma = "all"
bracketSpacing = true
bracketSameLine = false
arrowParens = "always"
requirePragma = false
insertPragma = false
proseWrap = "preserve"
htmlWhitespaceSensitivity = "css"
vueIndentScriptAndStyle = false
endOfLine = "lf"
embeddedLanguageFormatting = "off"
singleAttributePerLine = true
